services:
  influxdb:
    image: influxdb:2.7.10
    container_name: influxdb
    ports:
      - '8086:8086'
    volumes:
      - type: volume
        source: influxdb2-data
        target: /var/lib/influxdb2
      - type: volume
        source: influxdb2-config
        target: /etc/influxdb2
      - type: volume
        source: influxdb2-backup
        target: /backups
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: "***PASS****"
      DOCKER_INFLUXDB_INIT_ORG: my-init-org
      DOCKER_INFLUXDB_INIT_BUCKET: my-init-bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "*****"
    restart:
      always
  grafana:
    image: grafana/grafana:11.2.2
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
  homedata:
    image: homedata
    container_name: homedata
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DOTNET_ENVIRONMENT: "Production"
      "dataAccess:url": "http://influxdb:8086"
      "dataAccess:apiToken": "*****APITOKEN*****"
    restart: always # unless-stopped      
    networks:
      - home-data-network
    depends_on:
      influxdb:
        condition: service_started
networks:
  home-data-network:

volumes:
  rediscert:
  redisdata:
  influxdb2-data:
  influxdb2-config:
  influxdb2-backup:
  grafana-storage:
  
