services:
  timescaledb:
    container_name: timescaledb
    image: timescale/timescaledb:latest-pg17
    environment:
      - POSTGRES_PASSWORD=h0me_data_g0es
    ports:
      - '5432:5432'
    volumes:
      - timescale-data:/var/lib/postgresql/data
volumes:
  timescale-data: